[tools]
1password = "latest"
bat = "latest"
claude = "latest"
codex = "latest"
dust = "latest"
gh = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
yazi = "latest"
