[tools]
1password = "latest"
"aqua:dalance/procs" = "latest"
bat = "latest"
claude = "latest"
codex = "latest"
dust = "latest"
eza = "latest"
gh = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
yazi = "latest"
fd = "latest"
ripgrep = "latest"
zoxide = "latest"
delta = "latest"
sd = "latest"
bottom = "latest"
tokei = "latest"
hyperfine = "latest"
gitui = "latest"
fzf = "latest"
